language: python
python:
  - "2.7"
# command to install dependencies
before_install:
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse"
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
- sudo apt-get update
- sudo apt-get install $(cat install/files/deb-packages_requirements.txt)
- sudo apt-get install libstdc++6
install: "pip install -r install/files/python_requirements.txt"
# command to run tests
script: pytest
# CodeCLimate for test coveragek
addons:
    code_climate:
        repo_token: d885ae74b4a0d071454ca6791b28aa3684d21a1003ac6011ddb65160529e9309
