---
# ---------------------------
# JARVIS default settings
# Use YAML syntax
# ---------------------------


# This is the trigger that will catch your magic work to wake up JARVIS
default_trigger: "snowboy"
# This is the STT that will be used by default
default_speech_to_text: "google"
# This is the default TTS that will be used by JARVIS to talk.
default_text_to_speech: "pico2wave"

# When jarvis detect the hotword/trigger, he will select randomly a phrase in the following list
# to notify the user that he's listening for orders
random_wake_up_answers:
  - "Oui monsieur?"
  - "Je vous écoute"
  - "Monsieur?"
  - "Que puis-je faire pour vous?"
  - "J'écoute"
  - "Oui?"

# Spreech to Text engines configuration
# Available engine are:
# - google (via SpeechRecognition)
# -
speech_to_text:
  - google:
      language: "fr-FR"
  - wit:
      key: "B5JI3YUSLYOYWNIDBINBVM34XUODME2K"
  - bing: # API not working : credential fails ..
      key: "9e48ddaf75904838bedc11aea6b36fb0"
  - apiai: # Fail retriving the text from the audio file ..
      key: "e0cbff154af44944a6b9f82c0668b527"
      language: "fr"
  - houndify: # In the online documentation but Not implemented yet in the speech recognition lib ..?
      key: "7zj90T7qAV74OYXk4X4vI2Xhk7wPsJu4aEZ0G5Ll-BMmV1JGtFpCxtSH9SmTY4G3bpEJ7a5y_GTQid-CAKI6vw=="
      client_id: "lN4JXeaSticbSo9-llczbA=="


# Text to Spreech engines configuration
# Available engine are:
# - pico2wave
# - voxygen
text_to_speech:
  - pico2wave:
      language: "fr"
      cache: True
  - voxygen:
      language: "fr"
      voice: "michel"
      cache: True

# Trigger engine configuration
# Available engine are:
# - snowboy
triggers:
  - snowboy:
      pmdl_file: "trigger/snowboy/resources/jarviss.pmdl"