---
# JARVIS default settings
# Use YAML syntax

# This is the snowboy hotword file used to wake up and listen for a new order
trigger:
  name: "jarviss.pmdl"

# Default Spreech to Text engine
# Available engine are:
# - google (via SpeechRecognition)
# -
speechToText:
  name: "google"
  args:
    language: "fr-FR"


# Default Text to Spreech engine
# Available engine are:
# - pico2wave
textToSpeech:
  name: "pico2wave"